export { default as Home } from './HomePage'
export { default as About } from './About'
export { default as Destinations } from './Destinations'
export { default as Blog } from './Blog'
export { default as Login } from './Login'
export { default as Register } from './Register'